name: Semgrep Security Scan

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  semgrep:
    name: Scan with Semgrep
    runs-on: ubuntu-latest
    
    # Skip bot commits
    if: github.actor != 'dependabot[bot]'
    
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Semgrep
        run: |
          semgrep scan \
            --config p/security-audit \
            --config p/owasp-top-ten \
            --config p/nodejs \
            --config p/javascript \
            --error \
            --verbose
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

